export const TIMELINE_CREATE_REQUEST = 'TIMELINE_CREATE_REQUEST';
export const TIMELINE_CREATE_SUCCESS = 'TIMELINE_CREATE_SUCCESS';
export const TIMELINE_CREATE_FAIL = 'TIMELINE_CREATE_FAIL';

export const TIMELINE_DELETE_REQUEST = 'TIMELINE_DELETE_REQUEST';
export const TIMELINE_DELETE_SUCCESS = 'TIMELINE_DELETE_SUCCESS';
export const TIMELINE_DELETE_FAIL = 'TIMELINE_DELETE_FAIL';

export const TIMELINE_OPEN_REQUEST = 'TIMELINE_OPEN_REQUEST';
export const TIMELINE_OPEN_SUCCESS = 'TIMELINE_OPEN_SUCCESS';
export const TIMELINE_OPEN_FAIL = 'TIMELINE_OPEN_FAIL';
export const TIMELINE_OPEN_CLEAR = 'TIMELINE_OPEN_CLEAR';

export const TIMELINE_LIST_REQUEST = 'TIMELINE_LIST_REQUEST';
export const TIMELINE_LIST_SUCCESS = 'TIMELINE_LIST_SUCCESS';
export const TIMELINE_LIST_FAIL = 'TIMELINE_LIST_FAIL';

export const TIMELINE_UPDATE_REQUEST = 'TIMELINE_UPDATE_REQUEST';
export const TIMELINE_UPDATE_SUCCESS = 'TIMELINE_UPDATE_SUCCESS';
export const TIMELINE_UPDATE_FAIL = 'TIMELINE_UPDATE_FAIL';
