export const GRID_VIEW_MODE_HOME = 'GRID_VIEW_MODE_HOME';
export const LIST_VIEW_MODE_HOME = 'GRID_VIEW_MODE_HOME';
export const TABLE_VIEW_MODE_HOME = 'GRID_VIEW_MODE_HOME';

export const TIMELINE_COLOR_PRESET = 'TIMELINE_COLOR_PRESET';