export const data = [
    {
        title: 'Nature\'s Wonders',
        description: 'Witness the awe-inspiring beauty of Mother Nature through breathtaking landscapes and wildlife.',
        updated: '09/06/2023',
        created: '09/06/2023',
        variant: 'success',
        border: 'dark',
        img: 'https://images.pexels.com/photos/4652275/pexels-photo-4652275.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
    },
    {
        title: 'Mind-Expanding Books',
        description: 'Embark on a literary journey and explore captivating worlds through the pages of extraordinary books.',
        updated: '10/06/2023',
        created: '10/06/2023',
        variant: 'dark',
        border: 'light',
    },
    {
        title: 'Epic Adventure',
        description: 'Embark on a thrilling journey to uncharted territories and discover hidden treasures.',
        updated: '01/06/2023',
        created: '01/06/2023',
        variant: 'light',
        border: 'light',
        img: 'https://images.pexels.com/photos/2397414/pexels-photo-2397414.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
    },
    {
        title: 'Inspiring Tales',
        description: 'Delve into a collection of heartwarming stories that will touch your soul.',
        updated: '02/06/2023',
        created: '02/06/2023',
        variant: 'danger',
        border: 'warning',
        img: 'https://images.pexels.com/photos/159862/art-school-of-athens-raphael-italian-painter-fresco-159862.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1https://images.pexels.com/photos/159862/art-school-of-athens-raphael-italian-painter-fresco-159862.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'

    },
    {
        title: 'Fitness Revolution',
        description: 'Revamp your lifestyle with a comprehensive fitness program designed to transform your body and mind.',
        updated: '03/06/2023',
        created: '03/06/2023',
        variant: 'warning',
        border: 'success',
    },
    {
        title: 'Thrills and Chills',
        description: 'Experience spine-tingling suspense and adrenaline-pumping action in a collection of gripping stories.',
        updated: '04/06/2023',
        created: '04/06/2023',
        variant: 'secondary',
        border: 'dark',
    },
    {
        title: 'Mindful Living',
        description: 'Discover the path to inner peace and happiness through mindfulness practices and meditation.',
        updated: '05/06/2023',
        created: '05/06/2023',
        variant: 'info',
        border: 'info',
    },
    {
        title: 'Artistic Exploration',
        description: 'Immerse yourself in the vibrant world of art and discover your creative genius.',
        updated: '06/06/2023',
        created: '06/06/2023',
        variant: 'light',
        border: 'danger',
    },
    {
        title: 'Culinary Delights',
        description: 'Embark on a gastronomic adventure and savor the exquisite flavors from around the world.',
        updated: '07/06/2023',
        created: '07/06/2023',
        variant: 'info',
        border: 'info',
    },
    {
        title: 'Global Cultures',
        description: 'Dive into the rich tapestry of global cultures and celebrate the diversity that unites us all.',
        updated: '11/06/2023',
        created: '11/06/2023',
        variant: '',
        border: 'secondary',
    },
    {
        title: 'Music Melodies',
        description: 'Let the rhythmic harmonies transport you to a world filled with soul-stirring melodies.',
        updated: '12/06/2023',
        created: '12/06/2023',
        variant: 'info',
        border: 'warning',
    },
    {
        title: 'Wellness Retreat',
        description: 'Escape the daily hustle and immerse yourself in a rejuvenating retreat for mind, body, and soul.',
        updated: '13/06/2023',
        created: '13/06/2023',
        variant: 'warning',
        border: 'dark',
    },
    {
        title: 'Entrepreneurship Masterclass',
        description: 'Unlock the secrets to entrepreneurial success and unleash your business acumen.',
        updated: '14/06/2023',
        created: '14/06/2023',
        variant: '',
        border: 'primary',
    },
    {
        title: 'Space Exploration',
        description: 'Embark on an interstellar adventure and uncover the mysteries of the vast cosmos.',
        updated: '15/06/2023',
        created: '15/06/2023',
        variant: 'primary',
        border: 'light',
    },
    {
        title: 'Mystical Legends',
        description: 'Explore the mythical realms of ancient legends and encounter legendary creatures.',
        updated: '16/06/2023',
        created: '16/06/2023',
        variant: '',
        border: 'dark',
    },
    {
        title: 'Photography Journeys',
        description: 'Capture the essence of life through the lens and embark on captivating photography adventures.',
        updated: '17/06/2023',
        created: '17/06/2023',
        variant: 'info',
        border: 'warning',
    },
    {
        title: 'Inspirational Quotes',
        description: 'Discover a collection of powerful quotes that will uplift and motivate you in every aspect of life.',
        updated: '18/06/2023',
        created: '18/06/2023',
        variant: '',
        border: 'secondary',
    }
];